language: julia

os:
  - osx
  - linux

julia:
  - 0.6

notifications:
  email: false

before_install:
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
   - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; sudo apt-get install -y hdf5-tools; fi
   - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew cask uninstall --force oclint && brew install gcc && brew install hdf5; fi

script:
    - julia -p 4 --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.add("MAT"); Pkg.build("Meganet"); Pkg.test("Meganet";coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Meganet")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
